(() => {
  const AutoFillExt = (globalThis.AutoFillExt = globalThis.AutoFillExt || {});
  const Excel = (AutoFillExt.excel = AutoFillExt.excel || {});

  Excel.allowedValues = Object.freeze({
    SENIORITY_LEVELS: ["JUNIOR", "SEMI-SENIOR", "SENIOR"],
    LANGUAGES: [
      "C++",
      "Java SE",
      "Java",
      "Python",
      "GO",
      "C# (.NET Framework)",
      "CL",
      "Elixir",
      "RPG/ILE",
      "javascript",
      "Cobol",
      "Dart",
      "Typescript",
      "Fundamentos CSS",
      "Fundamento CSS",
      "React",
      "Fundamentos HTML",
      "Fundamento HTML",
      "Conceptos generales Programacion reactiva",
      "SQL",
      "XPATH",
      "Kotlin",
      "Objective C",
      "Swift (Lenguaje)",
      "Finacle Scripting",
    ],
    DATABASES: ["SQL Server", "PostgreSQL", "MySQL", "DynamoDB", "DB2", "IBM Cloudant", "MongoDB", "ORACLE", "REDIS", "Couchbase Mobile", "LevelDB", "SQLite"],
    APPLICATIONS: ["Artifactory", "SWIFT", "Amazon EC2", "Micro Focus Extra! X-treme (MyExtra)", "DataPower", "Power Apps", "DYNATRACE"],
    FRAMEWORKS: [
      "Angular",
      "ASP MVC",
      "BDD Framework",
      "Chaos Engineering / Reducing Toil / SRE",
      "Data Driven Framework",
      "Django",
      "Express",
      "Flask",
      "Flutter",
      "FRAMEWORK DE AUTOMATIZACION: SERENITY",
      "Karate Framework",
      "Next.js (SSR)",
      "No SQL",
      "NPA/NHibernate",
      "Pandas",
      "Playwright",
      "QUARKUS",
      "Redux",
      "Scikit-learn",
      "SLIs / SLOs / Blameless Postmortems / Error Budgets / SRE",
      "Spring Boot",
      "Spring Cloud",
      "Spring Framework",
      "Spring Web",
      "Universal (SSR)",
      "Winium",
    ],
    PLATFORMS: [
      "AIX",
      "CLEAR PATH",
      "Docker",
      "Kubernetes",
      "Apache Kafka",
      "Apache Tomcat",
      "IIS",
      "Node js",
      "Spark",
      "WAS",
      "WMQ",
      "Mockito",
      "PowerMock",
      "AWS RDS",
      "Kobiton",
      "Prometheus",
      "Bizagi Process Modeler",
      "AWS Essentials",
      "ISERIES",
      "RPA",
    ],
    TOOLS: [
      "SonarQube",
      "Analisis Estatico (SonarQube)",
      "Appium",
      "Gradle",
      "GraphQL",
      "NPM",
      "Postman",
      "Rabbit MQ",
      "RabbitMQ",
      "Selenium",
      "Git",
      "Junit",
      "Webpack",
      "UrbanCode",
      "WebSocket",
      "Jscrambler",
      "Azure DevOps",
      "SoapUI",
      "GoAnywhere",
      "Android Studio",
      "ESLint",
      "JSHint",
      "Prettier",
      "Grafana",
      "Thanos",
      "POWER AUTOMATE",
      "Google Analitics",
      "I-reports IDE",
      "SQL Developer",
    ],
    OTHERS: [
      "AMQP",
      "Apache Camel",
      "OAuth 2.0",
      "OpenAPI",
      "Caching",
      "LocalStorage",
      "Service Worker",
      "PWA",
      "DDD",
      "SOLID",
      "JMS",
      "Sterling",
      "DOM y Browser Engine",
      "Event-driven Architecture (EDA)",
      "Flex",
      "Arquitectura de microservicios",
      "Murex AWS Essentials",
      "BDD (Gherkin / Serenity)",
      "DevOps CI",
      "DevOps CT",
      "Patron de diseno ScreenPlay",
      "Pruebas Unitarias",
      "REST",
      "WinAppDriver",
      "Azure Active Directory",
      "Jmeter",
      "OpenID",
      "OWASP",
      "Despliegue en Tiendas",
      "Device Farm",
      "Material Design",
      "Mobile First Design",
      "Push Notification",
      "Responsive Design",
      "Xamarin",
      "Certificacion en AWS Solutions Architect - Associate",
      "Especializacion o Maestria en: Tecnologias de Informacion, Desarrollo y Arquitectura de Software",
      "DESIGN THINKING",
      "Patrones de diseno",
      "DevOps",
      "Analitica",
      "Blockchain",
      "Microservicios",
      "SOA",
      "Clean Architecture",
      "Arquitectura Reactiva - Tacticas Arquitectura",
      "DISENO ORIENTADO A OBJETOS",
      "Inteligencia de negocios (Business Intelligence - BI)",
      "INTEGRACION API",
      "ARQUITECTURA CLOUD",
      "ARQUITECTURA DE SOFTWARE",
      "API GATEWAY",
      "Acceso Remoto",
      "Analisis de datos",
      "API",
      "Certificados digitales",
      "Direccionamiento/subneting/vlan/mac",
      "EXCEL",
      "Fundamentos basicos financieros",
      "Lectura de logs",
      "Metodologias agiles",
      "Protocolos de comunicacion segura (SSL/TLS/FTP/HTTPS)",
      "Automatizacion",
      "Finacle FIUI",
      "Finacle Pagos",
      "Finacle préstamos",
      "Finacle productos trade",
      "Gherkin / Cucumber",
      "Pruebas de Performance",
      "SOAP",
      "WEB SECURITY AND THE OWASP TOP 10: THE BIG PICTURE",
    ],
  });
})();
